#ifndef DEFINITIONS_H
#define DEFINITIONS_H

// Pin definitions
#define I2C_SDA_PIN 21
#define I2C_SCL_PIN 22
#define SERVO_OE_PIN 19
#define BUZZER_PIN 12

// I2C device addresses
#define I2C_SERVO_ADDRESS 0x40
#define I2C_DISPLAY_ADDRESS 0x3C

// UDP ports
#define UDP_IN_PORT 21370
#define UDP_OUT_PORT 21371

// STATUS_MESSAGE_BYTE_LOCATIONS
#define STATUS_MSG_FLAGS 1
#define STATUS_MSG_POWER 2
#define STATUS_MSG_RSSI 3

// Servo channels
#define SERVO_CHANNEL_FRONT_LEFT_WHEEL_VEL 0
#define SERVO_CHANNEL_FRONT_RIGHT_WHEEL_VEL 1
#define SERVO_CHANNEL_REAR_RIGHT_WHEEL_VEL 2
#define SERVO_CHANNEL_REAR_LEFT_WHEEL_VEL 3
#define SERVO_CHANNEL_FRONT_LEFT_WHEEL_ANGLE 4
#define SERVO_CHANNEL_FRONT_RIGHT_WHEEL_ANGLE 5
#define SERVO_CHANNEL_REAR_RIGHT_WHEEL_ANGLE 6
#define SERVO_CHANNEL_REAR_LEFT_WHEEL_ANGLE 7

// Wheel indices
#define FRONT_LEFT 0
#define FRONT_RIGHT 1
#define REAR_RIGHT 2
#define REAR_LEFT 3

#endif // DEFINITIONS_H